### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [bessemHmidi/AngularBeans#1]
hi, thanks for this project i will be test the demo app and when i deploye application i have this issus 
angular-beans.js not found

**Comment by bessemHmidi** [comment]
ok what is the app server and u used the dependency in your pom? if yes you
need additional info about the repo bcs it is on the staggin maven repo
(not in central yet)

**Comment by sidahmedbenkhaoua** [comment]
i used your project as depandancies

**Comment by bessemHmidi** [comment]
désolé du silence j’étais occupé par mon voyage de retour.

donc ce que je voulais dire c'est :

pour qu'un projet soit utilisé comme dépendance maven il faut :
-soit qu'il soit dans apache CENTRAL(le repos par défaut).

-soit que tu précise le serveur de dépôt explicitement.

pour mon cas le projet est dans un repos temporaire, (Stagging) il n'as pas
encore été promus au CENTRAL car il manque la javaDoc

(une de leurs conditions) mais ca sera réglé d'ici peu.

pour la démos c'est normale que ca marche pour moi parce que AngularBeans
est sur mon repos local (sur ma machine).

pour résumé:

1- utilise la version SNAPSHOT pour A.Beans
2- ajoute le repos des snapshot.

---

<dependencies>

<dependency>
<groupId>javax</groupId>
<artifactId>javaee-web-api</artifactId>
<version>7.0</version>
<scope>provided</scope>
</dependency>

<dependency>
<groupId>com.github.bessemHmidi</groupId>
<artifactId>angularBeans</artifactId>
<version>_1.0.1-SNAPSHOT_</version>
</dependency>

</dependencies>

_<repositories>_
- <repository>*
- <id>AngularBeanRepo</id>*
- <name>snapshots-repo</name>*
- <url>https://oss.sonatype.org/content/repositories/snapshots
  https://oss.sonatype.org/content/repositories/snapshots</url>*
- </repository>*
- </repositories>  *

---

dis moi si c'est bon :)

On Sun, May 24, 2015 at 8:41 PM, Benkhaoua notifications@github.com wrote:

> i used your project as depandancies
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bessemHmidi/AngularBeans/issues/1#issuecomment-105056782
> .

## 

_Hmidi Bessem_
_CUP JEE/NET_
_Technologue à ESPRIT_
_98 709 610_

**Comment by IOAyman** [comment]
Or, to use the local version of dependencies,  you could first do a `mvn clean install` in the _angular-beans_ project directory.  
You can THEN, compile the _demoApp_ project with no problems :wink:

**Comment by bessemHmidi** [comment]
haha, ofc, bcs you will have _angular-beans in your_ local repos :)

it easier in fact :)

On Mon, May 25, 2015 at 5:50 PM, Ayman Nedjmeddine <notifications@github.com

> wrote:
> 
> Or, to use the local version of dependencies, you could do a mvn clean
> install in the _angular-beans_ project directory.
> 
> You can THEN, compile the _demoApp_ project with no problems [image:
> :wink:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bessemHmidi/AngularBeans/issues/1#issuecomment-105266786
> .

## 

_Hmidi Bessem_
_CUP JEE/NET_
_Technologue à ESPRIT_
_98 709 610_
