### ISSUE TITLE
angular-base does not compile (cannot find Could not find artifact com.google.javascript:closure-compiler:jar:1.0-SNAPSHOT)

### ISSUE THREAD

**Issue by rbuitragoc** [bessemHmidi/AngularBeans#19]
I've searched a bit and found out that the issue is that the Closure Compile library is using a different versioning scheme, hence the `1.0-SNAPSHOT` is not available on public maven repositories. Nevertheless, they maintain the project with relative consistency, and there's a version as specified [here](https://github.com/google/closure-compiler/wiki/Maven). I changed that in my local `pom.xml` and it started to compile with no issues. This is the resulting dependency tree: 

``` Shell
[INFO] ------------------------------------------------------------------------
[INFO] Building angularBeans 1.0.2-RC1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ angularBeans ---
[INFO] com.github.bessemHmidi:angularBeans:jar:1.0.2-RC1
[INFO] +- javax:javaee-web-api:jar:7.0:provided
[INFO] +- com.google.javascript:closure-compiler:jar:v20141023:compile
[INFO] |  +- com.google.javascript:closure-compiler-externs:jar:v20141023:compile
[INFO] |  +- args4j:args4j:jar:2.0.26:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
[INFO] |  \- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] \- com.google.code.gson:gson:jar:2.3:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by bessemHmidi** [comment]
Thanks, please initiate a PR (but can you tell me what app server you use ?)
bcs this version 1.0-SNAPSHOT was the only one who worked fine with
glassfish 4.1
and its weird that the prblm with that version (SNAPSHOT) has started few
day ago (like it has been remouved or smyhg??)

On Fri, Jul 10, 2015 at 4:17 PM, Rick Buitrago notifications@github.com
wrote:

> I've searched a bit and found out that the issue is that the Closure
> Compile library is using a different versioning scheme, hence the
> 1.-0-SNAPSHOT is not available on public maven repositories. There's,
> although the latest version as specified [image: here]
> https://github.com/google/closure-compiler/wiki/Maven. I changed that
> in my local pom.xml andit started to compile with no issues. This is the
> resulting dependency tree:
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building angularBeans 1.0.2-RC1
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ angularBeans ---
> [INFO] com.github.bessemHmidi:angularBeans:jar:1.0.2-RC1
> [INFO] +- javax:javaee-web-api:jar:7.0:provided
> [INFO] +- com.google.javascript:closure-compiler:jar:v20141023:compile
> [INFO] |  +- com.google.javascript:closure-compiler-externs:jar:v20141023:compile
> [INFO] |  +- args4j:args4j:jar:2.0.26:compile
> [INFO] |  +- com.google.guava:guava:jar:18.0:compile
> [INFO] |  +- com.google.protobuf:protobuf-java:jar:2.5.0:compile
> [INFO] |  - com.google.code.findbugs:jsr305:jar:1.3.9:compile
> [INFO] - com.google.code.gson:gson:jar:2.3:compile
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bessemHmidi/AngularBeans/issues/19.

## 

_Hmidi Bessem_

_98 709 610_
