### ISSUE TITLE
Unknown provider: notificationsServiceProvider <- notificationsService <- GrowlCtrl in demoApp

### ISSUE THREAD

**Issue by aschreque** [bessemHmidi/AngularBeans#2]
demoApp Version commit d658e500fac5a785a2ea87c91b6bc9637a2441a3
AngularBeans : version 1.0.1
J2EE stack :JBoss wildfly 8.2

After automatic redirect to login, nothing shows up.
Chrome Debugger activated dump a stack in AngularJS init 

Javascript log 
Error: [$injector:unpr] Unknown provider: notificationsServiceProvider <- notificationsService <- GrowlCtrl
http://errors.angularjs.org/1.3.15/$injector/unpr?p0=notificationsServiceProvider%20%3C-%20notificationsService%20%3C-%20GrowlCtrl
    at REGEX_STRING_REGEXP (angular.js:63)
    at angular.js:4015
    at Object.getService [as get](angular.js:4162)
    at angular.js:4020
    at getService (angular.js:4162)
    at Object.invoke (angular.js:4194)
    at $get.extend.instance (angular.js:8493)
    at angular.js:7739
    at forEach (angular.js:331)
    at nodeLinkFn (angular.js:7738)

**Comment by bessemHmidi** [comment]
can you tell me the appserver used and version and when you cloned the demo
app?

**Comment by bessemHmidi** [comment]
sorry i did'nt notice that you already gave me the details (with mobile phone)

i will check now . thnks

**Comment by bessemHmidi** [comment]
ok, try a new clone and clean install angular beans and re-import the
demoApp

normally this issue no longer existe on the last commit .

(try also to clean browser cache)

On Wed, Jun 3, 2015 at 11:15 AM, Bessem Hmidi bessem.hmidi@esprit.tn
wrote:

> can you tell me the appserver used and version and when you cloned the
> demo app?
> Le 3 juin 2015 10:59, "aschreque" notifications@github.com a écrit :
> 
> > demoApp Version commit d658e50
> > https://github.com/bessemHmidi/AngularBeans/commit/d658e500fac5a785a2ea87c91b6bc9637a2441a3
> > AngularBeans : version 1.0.1
> > J2EE stack :JBoss wildfly 8.2
> > 
> > After automatic redirect to login, nothing shows up.
> > Chrome Debugger activated dump a stack in AngularJS init
> > 
> > Javascript log
> > Error: [$injector:unpr] Unknown provider: notificationsServiceProvider <-
> > notificationsService <- GrowlCtrl
> > 
> > http://errors.angularjs.org/1.3.15/$injector/unpr?p0=notificationsServiceProvider%20%3C-%20notificationsService%20%3C-%20GrowlCtrl
> > http://errors.angularjs.org/1.3.15/%24injector/unpr?p0=notificationsServiceProvider%20%3C-%20notificationsService%20%3C-%20GrowlCtrl
> > at REGEX_STRING_REGEXP (angular.js:63)
> > at angular.js:4015
> > at Object.getService as get
> > at angular.js:4020
> > at getService (angular.js:4162)
> > at Object.invoke (angular.js:4194)
> > at $get.extend.instance (angular.js:8493)
> > at angular.js:7739
> > at forEach (angular.js:331)
> > at nodeLinkFn (angular.js:7738)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bessemHmidi/AngularBeans/issues/2.

## 

_Hmidi Bessem_
_CUP JEE/NET_
_Technologue à ESPRIT_
_98 709 610_

**Comment by bessemHmidi** [comment]
is this ok ??

**Comment by aschreque** [comment]
Hi,

I did a fresh clone and nothing has changed, clean up my m2 repository,  rebuild, republish... it's the same. 
I did not see a new commit since my previous checkout.

**Comment by bessemHmidi** [comment]
wildfly 8.2 need Beans.xml under META-INF, i added it and it's ok.

so you can  clone the demo app again (or add beans.xml)

**Comment by aschreque** [comment]
Working, thanks
