### ISSUE TITLE
are we re-generating the script each time we request "/angularBeans.js" ?

### ISSUE THREAD

**Issue by anaili** [bessemHmidi/AngularBeans#26]
As I'm seeing, we are calling to re-generate the script for each request to /angularBeans.js. I think it would be better if we have a sort of cache ?

**Comment by bessemHmidi** [comment]
AngularBeans already use a cache for 98% of the JS.
if a bean is a NGSessionScoped, and we need to reinitialise the models values for the generated services  from calling @NGModel annotated getter's, that's why we cannot make a caching for all the script. only for "statics" parts of it.
