### ISSUE TITLE
BeanValidationProcessor ignores invalid constraints

### ISSUE THREAD

**Issue by yesbutno** [bessemHmidi/AngularBeans#32]
Currently `BeanValidationProcessor` only maps BV constraints to ng constraints. Invalid values are ignored, e.g. `@Size(min=-5)`.
Shouldn't a `ValidationException` be thrown instead?

**Comment by bessemHmidi** [comment]
yes, totally agree :+1: but the validation exception is reserved to "user" values , instead we can create a new Exception "IncorrectValidationConstraint" for example (if something does not alraidy exist in bean validation api, i will check)

**Comment by bessemHmidi** [comment]
yes found it: http://docs.oracle.com/javaee/7/api/javax/validation/ValidationException.html

look at the direct subclasses part :)

**Comment by yesbutno** [comment]
So `ValidationExceptions` occur when values violate the constraint. This is what you mean by "user values", right? Sounds reasonable.
Then I see two candidates: `ConstraintDeclarationException` and `ConstraintDefinitionException`. Since using annotations is said to be a declarative approach I'd vote for `ConstraintDeclarationException` and reserve the other one for bugs in custom constraint definitions.

BTW: Hibernate Validator itself says:
`javax.validation.ValidationException: HV000032
[...]
Caused by: java.lang.IllegalArgumentException: HV000019: The min parameter cannot be negative.`

**Comment by bessemHmidi** [comment]
:100:

**Comment by bessemHmidi** [comment]
between you email is info@michael-kulla.com right, have you a gmail one?
