### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by PorkLip** [bessemHmidi/AngularBeans#48]
The license specified in the POM of angular-beans project is LGPL but the [LICENSE](https://github.com/bessemHmidi/AngularBeans/blob/master/LICENSE) file in the root of the [github project](https://github.com/bessemHmidi/AngularBeans) contains the GPL license!  I'm no lawyer but I think that using the GPL license makes it impossible to use AngularBeans as a library without also applying the GPL license to the "linking" software.
Is AngularBeans using GPL or LGPL?

**Comment by bessemHmidi** [comment]
Thank's a lot! PorkLip , it's weird that the GPL text was here from the begining it we did'nt notice it :+1: 

License text updated.
